#source 'https://github.com/CocoaPods/Specs.git'

platform  :ios, '10.0'
use_frameworks!

target 'KKRequestFramework' do

  pod 'AFNetworking'

end

target 'KKRequestLibrary' do

  pod 'AFNetworking'

end


target 'KKRequestDemo' do

#  pod 'KeKeRequest'
  pod 'KeKeRequest', :path => '../../KeKeRequest'

end
